services:
  nextapp:
    container_name: nextapp
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - goapp
  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgresql://lenar:3zSjEVjoHt06bhfVDRUEIStdsf50fAuD@dpg-crj0duaj1k6c73fir9vg-a.frankfurt-postgres.render.com/auth_ze0c'
    ports:
      - '8000:8000'
